services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: masterpass
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: healthChecker
    hostname: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U master -d healthChecker']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=masterpass
      - DATABASE_URL=postgresql://master:masterpass@postgres:5432/healthChecker
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./prisma:/app/prisma
      - .env:/app/.env
    hostname: backend

# volumes セクションを追加
volumes:
  postgres_data:
